// examples/tanstack-react-router/src/config/navigation.tsx
import * as Icon from '@ant-design/icons'
import { createNavo } from '@navojs/tanstack-react-router'
import type { ReactNode } from 'react'
// 从 router 导入 route 实例
import {
  aboutRoute,
  dashboardRoute,
  docApiRoute,
  docFaqRoute,
  docGuideRoute,
  documentsRoute,
  monitorRoute,
  permissionsRoute,
  systemRoute,
  userDetailRoute,
  userListRoute,
  usersRoute,
  workspaceRoute,
} from '../router'

declare module '@navojs/tanstack-react-router' {
  interface NavoMeta {
    icon?: ReactNode
  }
}

const i = (IconComp: React.ComponentType) => <IconComp />

export const navo = createNavo([
  {
    id: systemRoute.id,
    label: '系统管理',
    path: systemRoute.path,
    meta: { icon: i(Icon.SettingOutlined) },
    children: [
      {
        id: permissionsRoute.id,
        label: '权限管理',
        path: permissionsRoute.path,
        meta: { icon: i(Icon.LockOutlined) },
      },
      {
        id: usersRoute.id,
        label: '用户管理',
        path: usersRoute.path,
        meta: { icon: i(Icon.UserOutlined) },
        children: [
          {
            id: userListRoute.id,
            affiliated: true,
            label: '用户列表',
            path: userListRoute.path,
            resolve: 1,
          },
          {
            id: userDetailRoute.id,
            affiliated: true,
            label: '用户详情',
            path: userDetailRoute.path,
          },
        ],
      },
    ],
  },
  {
    id: workspaceRoute.id,
    label: '工作台',
    path: workspaceRoute.path,
    meta: { icon: i(Icon.DesktopOutlined) },
    children: [
      {
        id: dashboardRoute.id,
        label: '数据概览',
        path: dashboardRoute.path,
        meta: { icon: i(Icon.DashboardOutlined) },
      },
      {
        id: monitorRoute.id,
        label: '实时监控',
        path: monitorRoute.path,
        meta: { icon: i(Icon.MonitorOutlined) },
      },
      {
        id: documentsRoute.id,
        label: '文档中心',
        path: documentsRoute.path,
        resolve: 1,
        meta: { icon: i(Icon.FolderOutlined) },
        children: [
          {
            id: docGuideRoute.id,
            label: '使用指南',
            path: docGuideRoute.path,
            meta: { icon: i(Icon.FileTextOutlined) },
          },
          {
            id: docApiRoute.id,
            label: 'API文档',
            path: docApiRoute.path,
            meta: { icon: i(Icon.FileTextOutlined) },
          },
          {
            id: docFaqRoute.id,
            label: '常见问题',
            path: docFaqRoute.path,
            meta: { icon: i(Icon.FileTextOutlined) },
          },
        ],
      },
    ],
  },
  {
    id: aboutRoute.id,
    label: '关于',
    path: aboutRoute.path,
    meta: { icon: i(Icon.InfoCircleOutlined) },
  },
])

// examples/vue-router/src/config/navigation.tsx
import * as Icon from '@ant-design/icons-vue'
import { createNavo } from '@navojs/vue-router'
import type { VNode } from 'vue'
import About from '../pages/About'
import Dashboard from '../pages/Dashboard'
import DocApi from '../pages/DocApi'
import DocFaq from '../pages/DocFaq'
import DocGuide from '../pages/DocGuide'
import Monitor from '../pages/Monitor'
import Permissions from '../pages/Permissions'
import UserDetail from '../pages/UserDetail'
import UserList from '../pages/UserList'

declare module '@navojs/vue-router' {
  interface NavoMeta {
    icon?: VNode
  }
}

const i = (IconComp: typeof Icon.SettingOutlined) => <IconComp />

export const navo = createNavo([
  {
    id: 'system',
    label: '系统管理',
    path: 'system',
    meta: { icon: i(Icon.SettingOutlined) },
    children: [
      {
        id: 'permissions',
        label: '权限管理',
        path: 'permissions',
        meta: { icon: i(Icon.LockOutlined) },
        route: { component: Permissions },
      },
      {
        id: 'users',
        label: '用户管理',
        path: 'users',
        meta: { icon: i(Icon.UserOutlined) },
        children: [
          {
            id: 'user-list',
            affiliated: true,
            label: '用户列表',
            path: 'list',
            resolve: 1,
            route: { component: UserList },
          },
          {
            id: 'user-detail',
            affiliated: true,
            label: '用户详情',
            path: ':id',
            route: { component: UserDetail },
          },
        ],
      },
    ],
  },
  {
    id: 'workspace',
    label: '工作台',
    path: 'workspace',
    meta: { icon: i(Icon.DesktopOutlined) },
    children: [
      {
        id: 'dashboard',
        label: '数据概览',
        path: 'dashboard',
        meta: { icon: i(Icon.DashboardOutlined) },
        route: { component: Dashboard },
      },
      {
        id: 'monitor',
        label: '实时监控',
        path: 'monitor',
        meta: { icon: i(Icon.MonitorOutlined) },
        route: { component: Monitor },
      },
      {
        id: 'documents',
        label: '文档中心',
        path: 'documents',
        resolve: 1,
        meta: { icon: i(Icon.FolderOutlined) },
        children: [
          {
            id: 'doc-guide',
            label: '使用指南',
            path: 'guide',
            meta: { icon: i(Icon.FileTextOutlined) },
            route: { component: DocGuide },
          },
          {
            id: 'doc-api',
            label: 'API文档',
            path: 'api',
            meta: { icon: i(Icon.FileTextOutlined) },
            route: { component: DocApi },
          },
          {
            id: 'doc-faq',
            label: '常见问题',
            path: 'faq',
            meta: { icon: i(Icon.FileTextOutlined) },
            route: { component: DocFaq },
          },
        ],
      },
    ],
  },
  {
    id: 'about',
    label: '关于',
    path: 'about',
    meta: { icon: i(Icon.InfoCircleOutlined) },
    route: { component: About },
  },
])
