// examples/vue-router/src/App.tsx
import { NavoProvider, useCanAccess } from '@navojs/vue-router'
import { defineComponent, onMounted, watch } from 'vue'
import { RouterView } from 'vue-router'
import { navo } from './config/navigation'
import { usePermissions } from './store/permissions'

const AccessController = defineComponent({
  name: 'AccessController',
  setup() {
    const { enabledIds, initPermissions } = usePermissions()
    const onCanAccess = useCanAccess()

    onMounted(() => {
      initPermissions(navo.nodes)
      // 初始鉴权
      onCanAccess((node) => enabledIds.value.has(node.id))
    })

    watch(enabledIds, (ids) => {
      onCanAccess((node) => ids.has(node.id))
    })

    return () => null
  },
})

export default defineComponent({
  name: 'App',
  setup() {
    return () => (
      <NavoProvider navo={navo}>
        <AccessController />
        <RouterView />
      </NavoProvider>
    )
  },
})

// examples/react-router/src/App.tsx
import { NavoProvider, useCanAccess } from '@navojs/react-router'
import { useAtomValue, useSetAtom } from 'jotai'
import { useEffect } from 'react'
import { RouterProvider } from 'react-router'
import AppProvider from './AppProvider'
import router, { navo } from './router'
import { enabledPermissionIdsAtom, initPermissionsAtom } from './store/permissions'

function AccessController() {
  const onCanAccess = useCanAccess()
  const enabledIds = useAtomValue(enabledPermissionIdsAtom)
  const init = useSetAtom(initPermissionsAtom)

  useEffect(() => {
    init(navo.nodes)
  }, [init])

  useEffect(() => {
    onCanAccess((node) => enabledIds.has(node.id))
  }, [enabledIds])

  return null
}

export default function App() {
  return (
    <AppProvider>
      <NavoProvider navo={navo}>
        <AccessController />
        <RouterProvider router={router} />
      </NavoProvider>
    </AppProvider>
  )
}
