// examples/vue-router/src/layouts/Layout.vue
<template>
  <div class="layout">
    <header class="header">
      <div class="logo">Navo Vue Demo</div>
      <nav class="top-nav">
        <router-link
          v-for="nav in topNodes"
          :key="nav.id"
          :to="nav.path"
          class="top-nav-item"
          active-class="active"
        >
          {{ nav.label }}
        </router-link>
      </nav>
    </header>
    <div class="body">
      <aside v-if="sidebarNodes.length" class="sidebar">
        <router-link
          v-for="node in sidebarNodes"
          :key="node.id"
          :to="node.path"
          class="sidebar-item"
          active-class="active"
        >
          {{ node.label }}
        </router-link>
      </aside>
      <main class="content">
        <router-view />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMatchedNodes, useNavo } from '@navo/vue-router'
import { computed } from 'vue'

const { nodes: topNodes } = useNavo()
const matchedResult = useMatchedNodes()

const activeNav = computed(() => matchedResult.value.matchedNodes[0])
const sidebarNodes = computed(() => activeNav.value?.children ?? [])
</script>

<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: system-ui, sans-serif; }

.layout { display: flex; flex-direction: column; height: 100vh; }

.header {
  display: flex; align-items: center; height: 56px;
  background: #1e293b; color: #fff; padding: 0 24px; gap: 32px; flex-shrink: 0;
}
.logo { font-size: 18px; font-weight: 700; white-space: nowrap; }
.top-nav { display: flex; height: 100%; }
.top-nav-item {
  display: flex; align-items: center; padding: 0 20px; color: #94a3b8;
  text-decoration: none; font-size: 14px; border-bottom: 2px solid transparent;
  transition: color 0.2s, border-color 0.2s;
}
.top-nav-item:hover { color: #e2e8f0; }
.top-nav-item.active { color: #60a5fa; border-bottom-color: #60a5fa; }

.body { display: flex; flex: 1; overflow: hidden; }

.sidebar {
  width: 200px; background: #f8fafc; border-right: 1px solid #e2e8f0;
  padding: 12px 0; overflow-y: auto; flex-shrink: 0;
}
.sidebar-item {
  display: block; padding: 8px 24px; color: #475569; text-decoration: none;
  font-size: 14px; transition: background 0.15s;
}
.sidebar-item:hover { background: #e2e8f0; }
.sidebar-item.active { color: #2563eb; background: #eff6ff; font-weight: 600; }

.content { flex: 1; padding: 24px; overflow-y: auto; }
</style>

// examples/react-router/src/layouts/Layout.tsx
import { useMatchedNodes, useNavo } from '@navo/react-router'
import { Layout as AntLayout, Menu } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { Link, Outlet, useNavigate } from 'react-router'

const { Header, Sider, Content } = AntLayout

export default function Layout() {
  const navigate = useNavigate()
  const { nodes, getPathById } = useNavo()
  const { matchedNodes, matchedIds } = useMatchedNodes()
  const [openKeys, setOpenKeys] = useState<string[]>([])

  const activeNav = matchedNodes[0]
  const sidebarNodes = activeNav?.children ?? []

  // 当路由变化时，自动展开当前匹配的父菜单
  useEffect(() => {
    setOpenKeys(matchedIds.slice(0, -1))
  }, [matchedIds])

  const menuItems = useMemo(
    () =>
      sidebarNodes.map((n) => ({
        key: n.id,
        icon: n.meta?.icon,
        label: n.label,
        children: n.children?.map((c) => ({ key: c.id, icon: c.meta?.icon, label: c.label })),
      })),
    [sidebarNodes]
  )

  return (
    <AntLayout className="h-screen bg-slate-50">
      <Header className="flex items-center px-0 bg-slate-900 h-16 shrink-0">
        <div className="flex items-center px-6 w-64 shrink-0">
          <h1 className="text-lg font-bold text-white">Navo Demo</h1>
        </div>
        <div className="flex items-center h-full">
          {nodes.map((nav) => {
            const active = activeNav?.id === nav.id
            return (
              <Link
                key={nav.id}
                to={nav.path}
                className={`flex items-center gap-2 px-6 h-full text-sm font-medium border-b-2 transition-colors ${active ? 'text-blue-400 border-blue-400 bg-slate-800' : 'text-slate-300 border-transparent hover:text-white hover:bg-slate-800'}`}
              >
                <span className={active ? 'text-blue-400' : 'text-slate-400'}>
                  {nav.meta?.icon}
                </span>
                {nav.label}
              </Link>
            )
          })}
        </div>
      </Header>

      <AntLayout hasSider className="bg-slate-50 overflow-hidden flex-1">
        {sidebarNodes.length > 0 && (
          <Sider width={200} className="bg-white shadow-sm h-full">
            <Menu
              mode="inline"
              selectedKeys={[matchedIds.at(-1) ?? '']}
              openKeys={openKeys}
              onOpenChange={setOpenKeys}
              items={menuItems}
              onClick={({ key }) => {
                const path = getPathById(key)
                path && navigate(path)
              }}
              className="border-r-0 h-full"
            />
          </Sider>
        )}
        <Content className="p-6 overflow-auto">
          <Outlet />
        </Content>
      </AntLayout>
    </AntLayout>
  )
}
