// examples/tanstack-react-router/src/App.tsx
import { NavoProvider, useCanAccess } from '@navo/tanstack-react-router'
import { RouterProvider } from '@tanstack/react-router'
import { useAtomValue, useSetAtom } from 'jotai'
import { useEffect } from 'react'
import AppProvider from './AppProvider'
import { navo } from './config/navigation'
import router from './router'
import { enabledPermissionIdsAtom, initPermissionsAtom } from './store/permissions'

function AccessController() {
  const onCanAccess = useCanAccess()
  const enabledIds = useAtomValue(enabledPermissionIdsAtom)
  const init = useSetAtom(initPermissionsAtom)

  useEffect(() => {
    init(navo.nodes)
  }, [init])

  useEffect(() => {
    onCanAccess((node) => enabledIds.has(node.id))
  }, [enabledIds])

  return null
}

export default function App() {
  return (
    <AppProvider>
      <NavoProvider navo={navo}>
        <AccessController />
        <RouterProvider router={router} />
      </NavoProvider>
    </AppProvider>
  )
}

// examples/vue-router/src/App.vue
<template>
  <NavoProvider :navo="navo">
    <AccessController />
    <router-view />
  </NavoProvider>
</template>

<script setup lang="ts">
import { NavoProvider, useCanAccess } from '@navo/vue-router'
import { defineComponent, onMounted, watch } from 'vue'
import { navo } from './config/navigation'
import { usePermissions } from './store/permissions'

// 无渲染的鉴权控制组件（必须在 NavoProvider 内部）
const AccessController = defineComponent({
  name: 'AccessController',
  setup() {
    const { enabledIds, initPermissions } = usePermissions()
    const onCanAccess = useCanAccess()

    onMounted(() => {
      initPermissions(navo.nodes)
    })

    watch(enabledIds, (ids) => {
      onCanAccess((node) => ids.has(node.id))
    }, { immediate: true })

    return () => null
  },
})
</script>
